### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by dkouvdis** [elliotlewis/Google-Latlng-Lookup#2]
Hi.

I have added the files, but when I got to the fieldtype page. I see this message

Parse error: syntax error, unexpected T_VARIABLE, expecting T_FUNCTION in /blah/blah/blah/blah.dev/system11/expressionengine/third_party/google_latlng_lookup/ft.google_latlng_lookup.php on line 350

**Comment by bartverbruggen** [comment]
On line 347 there is a } that shouldn't be there. Don't know if the lower code should be inside the condition or not.

``` ruby
            if($this->EE->config->item('url_third_themes'))
            {
                $this->EE->cp->add_to_foot('<script type="text/javascript" src="'.$this->EE->config->item('url_third_themes').'google_latlng_lookup/js/google_latlng_lookup.js"></script>');
            }
                $this->EE->cp->add_to_foot('<script type="text/javascript" src="'.$this->EE->config->item('theme_folder_url').'third_party/google_latlng_lookup/js/google_latlng_lookup.js"></script>');
            }
```

**Comment by dkouvdis** [comment]
Hi.

Thanks for the reply.

I have noticed that too, removed it and I got another error. I will post it when I get home.

**Comment by elliotlewis** [comment]
Sorry for not replying to these. I don't get a notification from GitHub about issue so had no idea. I do on Devot-ee though. As these are very old issues, are you still getting the same issues, is it still relevant?!

**Comment by dkouvdis** [comment]
Sorry, cant remember :/ better close this
