### ISSUE TITLE
Pipe character | in address causes bug

### ISSUE THREAD

**Issue by GDmac** [elliotlewis/Google-Latlng-Lookup#4]
The explode() on '|' pipe character causes trouble when someone enters a pipe charachter in the address field. Maybe strip it from the address field in save/validate?

**Comment by elliotlewis** [comment]
I've add a 'fix'. I've decided to validate and post back a message rather than remove so the user knows what's happening. This could catch someone out if they don't notice the automatic removal. I've not heard of anyone using pipe's in an address so also assuming it's an edge case.

**Comment by GDmac** [comment]
very edge case, but there will be a company one day who will have the vertical bar in its name, and even now you can search for `Manhattan | New York` or `(manhattan) New York`
